<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Attraction;

class AttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attractions = [
            [
                'name' => 'Hurghada Grand Aquarium',
                'slug' => 'hurghada-grand-aquarium',
                'category' => 'Aquarium',
                'description' => 'A large aquarium showcasing over 1,200 marine animals across 100 species, featuring a shark tunnel and a rainforest exhibit.',
                'address' => 'Villages Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.20',
                'popularity' => 850,
                'is_featured' => true,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '09:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4740',
            ],
            [
                'name' => 'Giftun Islands',
                'slug' => 'giftun-islands',
                'category' => 'Island',
                'description' => 'A group of islands renowned for their pristine white-sand beaches and vibrant coral reefs, making them a popular destination for snorkeling and diving.',
                'address' => 'Off the coast of Hurghada, Red Sea, Egypt',
                'latitude' => '27.2000000',
                'longitude' => '33.9000000',
                'rating' => '4.80',
                'popularity' => 1200,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Mahmya Island',
                'slug' => 'mahmya-island',
                'category' => 'Island',
                'description' => 'An eco-tourism haven located on the Giftun Islands, offering clear turquoise waters, coral reefs, and a serene beach experience.',
                'address' => 'Part of the Giftun Islands, accessible via boat from Hurghada',
                'latitude' => '27.1900000',
                'longitude' => '33.9100000',
                'rating' => '4.60',
                'popularity' => 950,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 9200',
            ],
            [
                'name' => 'El Gouna',
                'slug' => 'el-gouna',
                'category' => 'Resort',
                'description' => 'A modern resort town known as the "Venice of the Red Sea," featuring lagoons, upscale hotels, and a variety of water sports.',
                'address' => '20 km north of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.4000000',
                'longitude' => '33.7000000',
                'rating' => '4.50',
                'popularity' => 1100,
                'is_featured' => true,
                'price_range' => '$$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 358 0075',
            ],
            [
                'name' => 'Sahl Hasheesh',
                'slug' => 'sahl-hasheesh',
                'category' => 'Resort',
                'description' => 'A luxurious resort area with a long promenade, beachfront dining, and clear waters ideal for snorkeling and diving.',
                'address' => '18 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.1000000',
                'longitude' => '33.8500000',
                'rating' => '4.40',
                'popularity' => 800,
                'is_featured' => true,
                'price_range' => '$$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 346 4600',
            ],
            [
                'name' => 'Makadi Water World',
                'slug' => 'makadi-water-world',
                'category' => 'Water Park',
                'description' => 'Egypt\'s largest water park, featuring over 50 slides and attractions suitable for all ages.',
                'address' => 'Madinat Makadi, Hurghada - Safaga Rd, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '4.30',
                'popularity' => 700,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 359 0225',
            ],
            [
                'name' => 'Jungle Aqua Park',
                'slug' => 'jungle-aqua-park',
                'category' => 'Water Park',
                'description' => 'A vast water park offering numerous slides, pools, and water games, making it a family-friendly destination.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '4.10',
                'popularity' => 650,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4601',
            ],
            [
                'name' => 'Hurghada Marina',
                'slug' => 'hurghada-marina',
                'category' => 'Marina',
                'description' => 'A vibrant marina area with yachts, restaurants, cafes, and shops, offering a lively atmosphere and sea views.',
                'address' => 'Marina Boulevard, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.00',
                'popularity' => 900,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 344 9201',
            ],
            [
                'name' => 'Mini Egypt Park',
                'slug' => 'mini-egypt-park',
                'category' => 'Museum',
                'description' => 'An open-air museum featuring miniature replicas of Egypt\'s most famous monuments and landmarks.',
                'address' => 'Makadi Bay, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '3.90',
                'popularity' => 500,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 100 002 2558',
            ],
            [
                'name' => 'El Dahar (Old Town)',
                'slug' => 'el-dahar-old-town',
                'category' => 'Historic',
                'description' => 'The old town of Hurghada, known for its traditional markets, narrow streets, and historical mosques.',
                'address' => 'El Dahar District, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.20',
                'popularity' => 600,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Hurghada Museum',
                'slug' => 'hurghada-museum',
                'category' => 'Museum',
                'description' => 'A museum showcasing artifacts from ancient Egypt to the modern era, highlighting the region\'s rich history.',
                'address' => 'Airport Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '3.80',
                'popularity' => 400,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 5544',
            ],
            [
                'name' => 'Sharm El Naga',
                'slug' => 'sharm-el-naga',
                'category' => 'Beach',
                'description' => 'A bay known for its beautiful coral reefs and crystal-clear waters, ideal for snorkeling and diving.',
                'address' => '40 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '26.9000000',
                'longitude' => '33.9000000',
                'rating' => '4.70',
                'popularity' => 750,
                'is_featured' => true,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Dolphin House (Sha\'ab El Erg)',
                'slug' => 'dolphin-house-shaab-el-erg',
                'category' => 'Diving Site',
                'description' => 'A popular dive site where dolphins are frequently spotted, offering a unique snorkeling and diving experience.',
                'address' => 'Off the coast of Hurghada, Red Sea, Egypt',
                'latitude' => '27.2000000',
                'longitude' => '33.9500000',
                'rating' => '4.90',
                'popularity' => 1000,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'El Mina Mosque',
                'slug' => 'el-mina-mosque',
                'category' => 'Religious',
                'description' => 'A prominent mosque in Hurghada known for its stunning architecture and cultural significance.',
                'address' => 'Hurghada Marina, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.10',
                'popularity' => 300,
                'is_featured' => false,
                'price_range' => 'Free',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Sindbad Submarine',
                'slug' => 'sindbad-submarine',
                'category' => 'Adventure',
                'description' => 'The only tourist submarine in the Red Sea, offering underwater tours to explore marine life without getting wet.',
                'address' => 'Sindbad Club, Village Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.30',
                'popularity' => 550,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 65 340 4222',
            ],
            [
                'name' => 'Desert Safari Adventures',
                'slug' => 'desert-safari-adventures',
                'category' => 'Adventure',
                'description' => 'Excursions into the Eastern Desert featuring quad biking, jeep tours, and camel treks, offering a glimpse into Bedouin life.',
                'address' => 'Various tour operators in Hurghada',
                'latitude' => '27.3000000',
                'longitude' => '33.6000000',
                'rating' => '4.50',
                'popularity' => 800,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '06:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 9203',
            ],
            [
                'name' => 'Senzo Mall',
                'slug' => 'senzo-mall',
                'category' => 'Shopping',
                'description' => 'A modern shopping mall featuring a variety of international and local brands, dining options, and entertainment facilities.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '3.70',
                'popularity' => 450,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '22:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4601',
            ],
            [
                'name' => 'Makadi Bay',
                'slug' => 'makadi-bay',
                'category' => 'Resort',
                'description' => 'A resort area known for its sandy beaches, coral reefs, and family-friendly hotels and activities.',
                'address' => '30 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '4.40',
                'popularity' => 700,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 359 0225',
            ],
            [
                'name' => 'Abu Tig Marina',
                'slug' => 'abu-tig-marina',
                'category' => 'Marina',
                'description' => 'A smaller, peaceful marina in El Gouna, offering stunning views of the Red Sea and a selection of restaurants and shops.',
                'address' => 'El Gouna, Red Sea Governorate, Egypt',
                'latitude' => '27.4000000',
                'longitude' => '33.7000000',
                'rating' => '4.20',
                'popularity' => 500,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 358 0075',
            ],
            [
                'name' => 'Saint Shenouda Coptic Orthodox Church',
                'slug' => 'saint-shenouda-coptic-orthodox-church',
                'category' => 'Religious',
                'description' => 'A Coptic Orthodox cathedral located in the El Dahar neighborhood, dedicated to Saint Shenouda.',
                'address' => 'El Dahar, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.00',
                'popularity' => 200,
                'is_featured' => false,
                'price_range' => 'Free',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Strait of Gubal',
                'slug' => 'strait-of-gubal',
                'category' => 'Diving Site',
                'description' => 'A narrow waterway known for its shipwrecks and diverse marine life, making it a popular diving destination.',
                'address' => 'Between the Sinai Peninsula and the Red Sea coast near Hurghada',
                'latitude' => '27.1000000',
                'longitude' => '34.0000000',
                'rating' => '4.60',
                'popularity' => 600,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Sinbad Aqua Park',
                'slug' => 'sinbad-aqua-park',
                'category' => 'Water Park',
                'description' => 'A family-friendly water park offering various slides, pools, and water activities suitable for all ages.',
                'address' => 'Village Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '3.90',
                'popularity' => 400,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 340 4222',
            ],
            [
                'name' => 'El Qoseir',
                'slug' => 'el-qoseir',
                'category' => 'Historic',
                'description' => 'One of the oldest cities on the western coast of the Red Sea, known for its historical significance and nearby diving sites.',
                'address' => 'Approximately 140 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '26.1000000',
                'longitude' => '34.3000000',
                'rating' => '4.10',
                'popularity' => 350,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Hurghada International Airport',
                'slug' => 'hurghada-international-airport',
                'category' => 'Transportation',
                'description' => 'The main airport serving Hurghada and the surrounding Red Sea resorts, facilitating both domestic and international flights.',
                'address' => 'Hurghada International Airport, Red Sea Governorate, Egypt',
                'latitude' => '27.1783000',
                'longitude' => '33.7994000',
                'rating' => '3.50',
                'popularity' => 1000,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 344 4444',
            ],
            [
                'name' => 'Sand City Hurghada',
                'slug' => 'sand-city-hurghada',
                'category' => 'Museum',
                'description' => 'An open-air museum featuring massive sand sculptures depicting historical and fictional characters.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '3.80',
                'popularity' => 300,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 100 382 3339',
            ],
        ];

        foreach ($attractions as $attractionData) {
            Attraction::create($attractionData);
        }
    }
}
