<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Attraction;

class AttractionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attractions = [
            [
                'name' => 'Hurghada Grand Aquarium',
                'slug' => 'hurghada-grand-aquarium',
                'category' => 'Aquarium',
                'description' => 'A large aquarium showcasing over 1,200 marine animals across 100 species, featuring a shark tunnel and a rainforest exhibit. Opened in January 2015, the Hurghada Grand Aquarium spans approximately 9.8 acres and houses over 1,200 animals across 100 species. The facility features 24 exhibits, including a shark tunnel, rainforest, and "Whale Valley," which showcases fossils from the Western Desert. Notable specimens include nurse sharks, stingrays, green sea turtles, shovelnose guitarfish, and eagle rays.',
                'address' => 'Villages Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.20',
                'popularity' => 850,
                'is_featured' => true,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '09:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4740',
            ],
            [
                'name' => 'Giftun Islands',
                'slug' => 'giftun-islands',
                'category' => 'Island',
                'description' => 'A group of islands renowned for their pristine white-sand beaches and vibrant coral reefs, making them a popular destination for snorkeling and diving. Comprising Giftun Kebir and Giftun Sughayer, these islands are part of a marine reserve in the Red Sea. They are renowned for their spectacular coral reefs and drop-offs teeming with marine life, making them popular destinations for snorkeling, diving, and sunbathing on pristine beaches.',
                'address' => 'Off the coast of Hurghada, Red Sea, Egypt',
                'latitude' => '27.2000000',
                'longitude' => '33.9000000',
                'rating' => '4.80',
                'popularity' => 1200,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Mahmya Island',
                'slug' => 'mahmya-island',
                'category' => 'Island',
                'description' => 'An eco-tourism haven located on the Giftun Islands, offering clear turquoise waters, coral reefs, and a serene beach experience. A small island off the coast of Hurghada, Mahmya Island offers access to some of the clearest, bluest waters of the Red Sea away from the busy nearby shores. Accessed by boat, the island has food and lounge facilities and places to get snorkel gear. Snorkeling in this area is a must, as the underwater life is bright, colorful, and active, and it is less crowded than in other snorkel spots. Dolphins are a frequent sighting and a highlight for many visitors.',
                'address' => 'Part of the Giftun Islands, accessible via boat from Hurghada',
                'latitude' => '27.1900000',
                'longitude' => '33.9100000',
                'rating' => '4.60',
                'popularity' => 950,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 9200',
            ],
            [
                'name' => 'El Gouna',
                'slug' => 'el-gouna',
                'category' => 'Resort',
                'description' => 'A modern resort town known as the "Venice of the Red Sea," featuring lagoons, upscale hotels, and a variety of water sports. Often referred to as the "Venice of the Red Sea," El Gouna is a privately owned luxury town north of Hurghada. It features lagoons, upscale resorts, and a vibrant nightlife, making it a hub for water sports like kitesurfing and paddleboarding.',
                'address' => '20 km north of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.4000000',
                'longitude' => '33.7000000',
                'rating' => '4.50',
                'popularity' => 1100,
                'is_featured' => true,
                'price_range' => '$$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 358 0075',
            ],
            [
                'name' => 'Sahl Hasheesh',
                'slug' => 'sahl-hasheesh',
                'category' => 'Resort',
                'description' => 'A luxurious resort area with a long promenade, beachfront dining, and clear waters ideal for snorkeling and diving. A luxurious resort area with a long promenade, beachfront dining, and clear waters ideal for snorkeling and diving. The area features pristine beaches, coral reefs, and family-friendly hotels and activities, making it perfect for both relaxation and adventure.',
                'address' => '18 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.1000000',
                'longitude' => '33.8500000',
                'rating' => '4.40',
                'popularity' => 800,
                'is_featured' => true,
                'price_range' => '$$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 346 4600',
            ],
            [
                'name' => 'Makadi Water World',
                'slug' => 'makadi-water-world',
                'category' => 'Water Park',
                'description' => 'Egypt\'s largest water park, featuring over 50 slides and attractions suitable for all ages. This beachfront water park in Hurghada is a favorite for many families visiting the area. With 46 different water slides, a wave pool, water cannons, a wave simulator for surfing, waterfalls throughout, and the turquoise ocean merely steps away, there are dozens of ways to enjoy the water. Brightly colored themed structures provide ways to stay cool while climbing and playing in the freshwater. Palm trees create shade in a lagoon area for when it\'s time to relax.',
                'address' => 'Madinat Makadi, Hurghada - Safaga Rd, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '4.30',
                'popularity' => 700,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 359 0225',
            ],
            [
                'name' => 'Jungle Aqua Park',
                'slug' => 'jungle-aqua-park',
                'category' => 'Water Park',
                'description' => 'A vast water park offering numerous slides, pools, and water games, making it a family-friendly destination. Situated in Hurghada on the Red Sea Coast of Egypt, Jungle Aqua Park is popular for its 35 water slides, 33 outdoor swimming pools, along with a fantastic range of sports and social activities for people of all ages. Guests are accommodated in spacious bungalow-style rooms situated around the hotel\'s wonderful gardens and pools. The beach is available at the sister property, Dana Beach, where you have a private area to get all your food and beverages.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '4.10',
                'popularity' => 650,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4601',
            ],
            [
                'name' => 'Hurghada Marina',
                'slug' => 'hurghada-marina',
                'category' => 'Marina',
                'description' => 'A vibrant marina area with yachts, restaurants, cafes, and shops, offering a lively atmosphere and sea views. Opened in 2008, Hurghada Marina serves as the recreational hub of the Red Sea resort. Centered around a 200-berth harbor and bordered by Marina Boulevard—a walkway flanked by palms, parks, and ochre-painted shops and residential blocks—the marina boasts an abundance of shopping, dining, and entertainment options.',
                'address' => 'Marina Boulevard, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.00',
                'popularity' => 900,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 344 9201',
            ],
            [
                'name' => 'Mini Egypt Park',
                'slug' => 'mini-egypt-park',
                'category' => 'Museum',
                'description' => 'An open-air museum featuring miniature replicas of Egypt\'s most famous monuments and landmarks. An open-air museum featuring miniature replicas of Egypt\'s most famous monuments and landmarks. It\'s an educational and entertaining attraction that offers a quick tour of Egypt\'s rich history and architecture, allowing visitors to see iconic structures like the Pyramids of Giza, the Sphinx, and other historical monuments in a compact, walkable format.',
                'address' => 'Makadi Bay, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '3.90',
                'popularity' => 500,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 100 002 2558',
            ],
            [
                'name' => 'El Dahar (Old Town)',
                'slug' => 'el-dahar-old-town',
                'category' => 'Historic',
                'description' => 'The old town of Hurghada, known for its traditional markets, narrow streets, and historical mosques. North of Hurghada\'s luxury resorts lies the Old Town of El Dahar, where visitors can find the city\'s most authentic restaurants and shops. A highlight of the area is a traditional Egyptian souk, crammed with shops selling leather, copper, papyrus, spices, and shisha pipes.',
                'address' => 'El Dahar District, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.20',
                'popularity' => 600,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Hurghada Museum',
                'slug' => 'hurghada-museum',
                'category' => 'Museum',
                'description' => 'A museum showcasing artifacts from ancient Egypt to the modern era, highlighting the region\'s rich history. Opened on February 29, 2020, the Hurghada Museum is the first antiquities museum in the Red Sea Governorate. It contains 1,791 artifacts that tell the history of Egypt, with exhibits ranging from ancient Egypt to modern history. The museum showcases items such as koptic icons, oil paintings, and a painted limestone bust of Meritamun, daughter and queen of Ramses II.',
                'address' => 'Airport Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '3.80',
                'popularity' => 400,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 5544',
            ],
            [
                'name' => 'Sharm El Naga',
                'slug' => 'sharm-el-naga',
                'category' => 'Beach',
                'description' => 'A bay known for its beautiful coral reefs and crystal-clear waters, ideal for snorkeling and diving. A bay known for its beautiful coral reefs and crystal-clear waters, ideal for snorkeling and diving. The area features excellent visibility and diverse marine life, making it a perfect spot for underwater photography and marine exploration.',
                'address' => '40 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '26.9000000',
                'longitude' => '33.9000000',
                'rating' => '4.70',
                'popularity' => 750,
                'is_featured' => true,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Dolphin House (Sha\'ab El Erg)',
                'slug' => 'dolphin-house-shaab-el-erg',
                'category' => 'Diving Site',
                'description' => 'A popular dive site where dolphins are frequently spotted, offering a unique snorkeling and diving experience. A marine area home to a large number of wild dolphins. Boat trips to the Dolphin House offer a chance to see these playful creatures in their natural habitat, with opportunities to swim alongside them. The site is renowned for its clear waters and abundant marine life, making it one of the most sought-after diving destinations in the Red Sea.',
                'address' => 'Off the coast of Hurghada, Red Sea, Egypt',
                'latitude' => '27.2000000',
                'longitude' => '33.9500000',
                'rating' => '4.90',
                'popularity' => 1000,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'El Mina Mosque',
                'slug' => 'el-mina-mosque',
                'category' => 'Religious',
                'description' => 'A prominent mosque in Hurghada known for its stunning architecture and cultural significance. Once a small fishing village, Hurghada has grown into the most toured destination in Egypt. The Abdel-Moneim Riad Mosque stands tall, offering visitors the chance to connect with the daily life and culture of the beach town. The intricate design of the mosque\'s classic Islamic architecture, combined with its scenic placement between the main street and the ocean, makes this a unique mosque to visit.',
                'address' => 'Hurghada Marina, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.10',
                'popularity' => 300,
                'is_featured' => false,
                'price_range' => 'Free',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Sindbad Submarine',
                'slug' => 'sindbad-submarine',
                'category' => 'Adventure',
                'description' => 'The only tourist submarine in the Red Sea, offering underwater tours to explore marine life without getting wet. Explore the underwater world without getting wet in the Sindbad Submarine. This adventure allows you to discover coral reefs and marine life at a depth of 22 meters, making it ideal for families and non-swimmers. The submarine provides panoramic views of the Red Sea\'s vibrant underwater ecosystem.',
                'address' => 'Sindbad Club, Village Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.30',
                'popularity' => 550,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 65 340 4222',
            ],
            [
                'name' => 'Desert Safari Adventures',
                'slug' => 'desert-safari-adventures',
                'category' => 'Adventure',
                'description' => ' Experience the beauty of the Egyptian desert with a safari tour, which may include activities like quad biking, camel riding, and visiting Bedouin villages. These adventures offer a unique opportunity to explore the vast desert landscapes, learn about traditional Bedouin culture, and enjoy thrilling activities in one of the world\'s most beautiful desert environments.',
                'address' => 'Various tour operators in Hurghada',
                'latitude' => '27.3000000',
                'longitude' => '33.6000000',
                'rating' => '4.50',
                'popularity' => 800,
                'is_featured' => true,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '06:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 344 9203',
            ],
            [
                'name' => 'Senzo Mall',
                'slug' => 'senzo-mall',
                'category' => 'Shopping',
                'description' => 'A modern shopping mall featuring a variety of international and local brands, dining options, and entertainment facilities. The mall provides a comprehensive shopping experience with numerous retail outlets, restaurants, cafes, and entertainment venues, making it a popular destination for both locals and tourists.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '3.70',
                'popularity' => 450,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '22:00',
),
                'website' => NULL,
                'phone' => '+20 65 346 4601',
            ],
            [
                'name' => 'Makadi Bay',
                'slug' => 'makadi-bay',
                'category' => 'Resort',
                'description' => ' A resort area known for its sandy beaches, coral reefs, and family-friendly hotels and activities. The bay offers pristine beaches, excellent diving and snorkeling opportunities, and a variety of water sports, making it an ideal destination for families and couples seeking both relaxation and adventure.',
                'address' => '30 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.0500000',
                'longitude' => '33.8000000',
                'rating' => '4.40',
                'popularity' => 700,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 359 0225',
            ],
            [
                'name' => 'Abu Tig Marina',
                'slug' => 'abu-tig-marina',
                'category' => 'Marina',
                'description' => 'A smaller, peaceful marina in El Gouna, offering stunning views of the Red Sea and a selection of restaurants and shops. This charming marina provides a more intimate setting compared to the main Hurghada Marina, with boutique shops, fine dining restaurants, and beautiful sunset views over the Red Sea.',
                'address' => 'El Gouna, Red Sea Governorate, Egypt',
                'latitude' => '27.4000000',
                'longitude' => '33.7000000',
                'rating' => '4.20',
                'popularity' => 500,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 358 0075',
            ],
            [
                'name' => 'Saint Shenouda Coptic Orthodox Church',
                'slug' => 'saint-shenouda-coptic-orthodox-church',
                'category' => 'Religious',
                'description' => 'A Coptic Orthodox cathedral located in the El Dahar neighborhood, dedicated to Saint Shenouda. This beautiful church serves as an important religious and cultural landmark in Hurghada, offering visitors insight into Egypt\'s Christian heritage and providing a peaceful place for worship and reflection.',
                'address' => 'El Dahar, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '4.00',
                'popularity' => 200,
                'is_featured' => false,
                'price_range' => 'Free',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Strait of Gubal',
                'slug' => 'strait-of-gubal',
                'category' => 'Diving Site',
                'description' => 'A narrow waterway known for its shipwrecks and diverse marine life, making it a popular diving destination. The strait is famous for its challenging diving conditions and the opportunity to explore historic shipwrecks, while also being home to a rich variety of marine species including sharks, rays, and colorful reef fish.',
                'address' => 'Between the Sinai Peninsula and the Red Sea coast near Hurghada',
                'latitude' => '27.1000000',
                'longitude' => '34.0000000',
                'rating' => '4.60',
                'popularity' => 600,
                'is_featured' => false,
                'price_range' => '$$$',
                'open_hours' => array (
  0 => '08:00',
  1 => '16:00',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Sinbad Aqua Park',
                'slug' => 'sinbad-aqua-park',
                'category' => 'Water Park',
                'description' => 'A family-friendly water park offering various slides, pools, and water activities suitable for all ages. The park features a variety of attractions including multiple slides, splash pools, and recreational areas designed to provide fun and entertainment for visitors of all ages, making it an ideal destination for families with children.',
                'address' => 'Village Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2574000',
                'longitude' => '33.8129000',
                'rating' => '3.90',
                'popularity' => 400,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '10:00',
  1 => '18:00',
),
                'website' => NULL,
                'phone' => '+20 65 340 4222',
            ],
            [
                'name' => 'El Qoseir',
                'slug' => 'el-qoseir',
                'category' => 'Historic',
                'description' => 'One of the oldest cities on the western coast of the Red Sea, known for its historical significance and nearby diving sites. El Qoseir has a rich history dating back to ancient times and was an important port for trade between Egypt and the Arabian Peninsula. Today, it offers visitors a glimpse into traditional Egyptian coastal life and serves as a gateway to some of the Red Sea\'s most pristine diving locations.',
                'address' => 'Approximately 140 km south of Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '26.1000000',
                'longitude' => '34.3000000',
                'rating' => '4.10',
                'popularity' => 350,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => NULL,
            ],
            [
                'name' => 'Hurghada International Airport',
                'slug' => 'hurghada-international-airport',
                'category' => 'Transportation',
                'description' => 'The main national flights  airport serving Hurghada and the surrounding Red Sea resorts, facilitating both domestic and international flights. As one of Egypt\'s busiest airports, it serves as the primary gateway for tourists visiting the Red Sea region, with modern facilities and connections to major cities worldwide.',
                'address' => 'Hurghada International Airport, Red Sea Governorate, Egypt',
                'latitude' => '27.1783000',
                'longitude' => '33.7994000',
                'rating' => '3.50',
                'popularity' => 1000,
                'is_featured' => false,
                'price_range' => '$$',
                'open_hours' => array (
  0 => '24/7',
),
                'website' => NULL,
                'phone' => '+20 65 344 4444',
            ],
            [
                'name' => 'Sand City Hurghada',
                'slug' => 'sand-city-hurghada',
                'category' => 'Museum',
                'description' => 'An open-air museum showcasing intricate sand sculptures created by artists from around the world. The sculptures depict famous landmarks, historical figures, and mythical creatures, offering a unique artistic experience. This attraction provides visitors with the opportunity to see incredible works of art made entirely from sand, showcasing the skill and creativity of international sand sculptors.',
                'address' => 'Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => '27.2500000',
                'longitude' => '33.8200000',
                'rating' => '3.80',
                'popularity' => 300,
                'is_featured' => false,
                'price_range' => '$',
                'open_hours' => array (
  0 => '09:00',
  1 => '17:00',
),
                'website' => NULL,
                'phone' => '+20 100 382 3339',
            ],
        ];

        foreach ($attractions as $attractionData) {
            Attraction::updateOrCreate(
                ['slug' => $attractionData['slug']],
                $attractionData
            );
        }
    }
}
