<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class BlogSeeder extends Seeder
{
    public function run()
    {
        $articles = [
            [
                'title' => 'Hurghada Beaches',
                'slug' => Str::slug('Hurghada Beaches'),
                'excerpt' => 'Golden sands and calm Red Sea waters.',
                'content' => 'Hurghada’s beaches stretch for miles along the Red Sea, offering golden sands, calm turquoise waters, and a relaxed atmosphere. Families enjoy safe swimming zones, while adventure seekers dive into water sports like snorkeling, windsurfing, and jet-skiing. Resorts provide private areas with loungers, beach bars, and umbrellas, while public beaches remain lively hubs of activity. Beyond the beach, boat tours and diving trips let visitors explore nearby coral reefs, islands, and marine life. The sunsets over the Red Sea are breathtaking, reflecting orange and pink hues across the calm waves. Hurghada has developed into a top destination for both relaxation and marine adventure, attracting tourists year-round. Its combination of natural beauty, warm climate, and accessible amenities make it a quintessential Red Sea destination. Walking along the shore, feeling the gentle waves, and exploring nearby islands creates memories that last a lifetime.',
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(['hurghada','beaches','red sea']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Arabic Culture and Traditions',
                'slug' => Str::slug('Arabic Culture and Traditions'),
                'excerpt' => 'Heritage of warmth, hospitality, and art.',
                'content' => 'Arabic culture in Egypt is a rich tapestry of history, tradition, and daily life. Hospitality is central, with guests welcomed with tea, food, and genuine warmth. Festivals, weddings, and communal meals reflect the deep-rooted values of generosity and respect. Music and storytelling preserve oral traditions while offering entertainment, from the rhythmic beats of percussion to poetic recitations. Markets, or souks, are cultural hubs where spices, textiles, and handicrafts reveal regional diversity. Arabic cuisine is an integral part of culture, from savory dishes like grilled seafood and falafel to sweet treats like baklava and basbousa. Religion, art, and family structures further define social norms, emphasizing community and continuity. Visitors experience a living culture where heritage is preserved yet integrated into contemporary life. Engaging with Arabic culture allows travelers to connect with people, history, and traditions in a meaningful way. Each city, town, or village offers unique customs and ceremonies that make every visit memorable.',
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(['arabic','culture','traditions']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Arabic Architecture Wonders',
                'slug' => Str::slug('Arabic Architecture Wonders'),
                'excerpt' => 'Intricate design and spiritual harmony.',
                'content' => 'Arabic architecture is a marriage of artistry, engineering, and spirituality. Its hallmarks include domes, arches, courtyards, minarets, and intricate geometric designs. Mosques, palaces, and traditional homes reflect centuries of aesthetic and functional innovation. Courtyards often feature water fountains and gardens, creating serene spaces within busy urban centers. The use of calligraphy and decorative motifs turns walls and ceilings into canvases conveying cultural stories and religious symbolism. Buildings are often oriented to take advantage of natural light and ventilation, demonstrating a thoughtful integration of environment and design. Urban landscapes showcase the evolution of styles from ancient Islamic, Ottoman, and modern interpretations. Visitors walking through historic cities witness the harmony between form, function, and spiritual meaning. Arabic architecture continues to inspire contemporary architects worldwide. Its beauty is as much about visual aesthetics as it is about fostering contemplation and community.',
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(['arabic','architecture','heritage']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Arabic Music Festivals',
                'slug' => Str::slug('Arabic Music Festivals'),
                'excerpt' => 'Celebrating rhythm, melody, and heritage.',
                'content' => 'Arabic music festivals are vibrant celebrations of history, melody, and culture. Traditional instruments like the oud, qanun, and darbuka blend with modern music elements, creating unique performances. Festivals often take place outdoors, under open skies, offering immersive experiences with colorful lights, performances, and communal gatherings. They provide a platform for both local and international artists to showcase talent and for audiences to experience traditional rhythms alongside contemporary fusion. Food, crafts, and dance accompany music, transforming the event into a multi-sensory cultural festival. These celebrations not only preserve heritage but also foster cross-cultural exchange. Visitors leave with memories of energy, movement, and rhythm that resonate beyond the festival. Arabic music festivals continue to evolve while maintaining the essence of centuries-old musical traditions. Each festival is a narrative, telling stories of history, society, and artistic innovation. The experience is both entertaining and educational, leaving a lasting impression.',
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(['arabic','music','festival']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Traditional Arabic Dances',
                'slug' => Str::slug('Traditional Arabic Dances'),
                'excerpt' => 'Expressive movements, vibrant costumes, storytelling.',
                'content' => 'Traditional Arabic dances are an expressive reflection of culture, storytelling, and heritage. Belly dance is the most recognized, featuring fluid torso movements and intricate rhythms, while folk dances vary across regions, each telling unique stories. Costumes are colorful and elaborate, enhancing the visual impact of every performance. Dances are integral to celebrations such as weddings, religious festivals, and communal gatherings, creating shared experiences of joy. Music accompanying the dances ranges from drums and percussion to wind instruments, setting both rhythm and emotional tone. Modern dance troupes sometimes integrate contemporary elements, blending old traditions with new expressions. Audiences engage both emotionally and physically, often joining in communal dances. These performances are also a form of cultural education, passing stories and values to younger generations. Traveling visitors witness the evolution of dance while understanding its roots in society. Traditional Arabic dances remain a living art, dynamic and adaptive yet firmly grounded in heritage.',
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(['arabic','dance','tradition']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red Sea Adventures',
                'slug' => Str::slug('Red Sea Adventures'),
                'excerpt' => 'Exciting water and marine activities.',
                'content' => 'The Red Sea is a haven for adventure seekers, offering activities like diving, sailing, snorkeling, and windsurfing. Its warm, crystal-clear waters provide unparalleled visibility for exploring coral reefs and vibrant marine life. Tourists can book guided diving trips to famous sites like Giftun Islands and Abu Ramada, where schools of colorful fish and unique coral formations abound. Boat excursions range from day trips to luxury sunset cruises, combining exploration with relaxation. Wind conditions are ideal for kitesurfing and sailing, attracting enthusiasts from around the world. Marine life enthusiasts often spend hours observing dolphins, turtles, and rare reef species. Beyond the water, the coastline offers desert excursions and Bedouin cultural experiences, creating a perfect balance between sea and land adventures. Photography enthusiasts find the region ideal for capturing vivid underwater and seascape images. Overall, the Red Sea delivers both thrills and serenity, ensuring memorable experiences for all ages.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['red sea','adventure','marine']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Snorkeling Spots in Hurghada',
                'slug' => Str::slug('Snorkeling Spots in Hurghada'),
                'excerpt' => 'Explore Hurghada’s vibrant coral reefs and shallow-water snorkeling spots.',
                'content' => 'Hurghada is world-famous for snorkeling, with reefs accessible right off the coast. The Giftun Islands, Mahmya, and Makadi Bay are among the most popular spots, offering shallow waters perfect for beginners while still delighting experienced snorkelers. Visitors can expect colorful coral gardens teeming with tropical fish, graceful rays, and occasional sea turtles. Guided trips often include glass-bottom boats, snorkeling tours, and eco-friendly excursions that highlight the region’s biodiversity. Even a short snorkeling session feels like entering another vibrant world beneath the waves, where every coral formation is alive with color and motion, making it an unforgettable adventure for all ages.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['snorkeling','coral','red sea','marine life']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Red Sea Fishes and Marine Life',
                'slug' => Str::slug('Red Sea Fishes and Marine Life'),
                'excerpt' => 'Discover the rich biodiversity of the Red Sea’s waters.',
                'content' => 'The Red Sea shelters an extraordinary variety of marine life, from colorful angelfish, parrotfish, and butterflyfish to dolphins, sea turtles, and rare reef species unique to this region. Snorkelers and divers alike describe the experience as entering a magical underwater world, where coral gardens form living mosaics teeming with movement and color. Dive sites such as Abu Ramada, Fanadir, and El Mina provide a mix of walls, reefs, and wrecks that cater to both beginners and professionals. Guided tours emphasize sustainable practices, ensuring the delicate ecosystem remains vibrant. Beyond the colorful fish, visitors may spot reef sharks, moray eels, and occasional manta rays, making every dive or snorkeling session an immersive journey into nature’s wonder.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['marine life','red sea','diving','snorkeling']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Hurghada Nightlife',
                'slug' => Str::slug('Hurghada Nightlife'),
                'excerpt' => 'Experience Hurghada’s vibrant evening and nightlife scene.',
                'content' => 'As the sun sets, Hurghada comes alive with a variety of nightlife options along its marinas and beachfront areas. Visitors can enjoy quiet seaside lounges, live music cafes, or high-energy clubs that host DJs and themed parties. The Marina Boulevard is especially popular for evening walks, where people can watch yachts, sip cocktails, and enjoy the sea breeze. Many resorts offer beach bars and open-air venues, ensuring there is something for everyone, whether you prefer romantic dinners, dancing under the stars, or socializing with fellow travelers. The blend of lively entertainment and relaxed coastal charm makes Hurghada’s nights as memorable as its days.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['nightlife','hurghada','marina','party']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Desert Safari Experiences',
                'slug' => Str::slug('Desert Safari Experiences'),
                'excerpt' => 'Unforgettable desert adventures beyond Hurghada’s coast.',
                'content' => 'Hurghada’s appeal extends beyond the sea, with desert safaris offering thrilling and serene experiences. Visitors can embark on jeep tours, quad biking adventures, or camel rides across golden sand dunes, guided by local experts. Many tours culminate in traditional Bedouin meals, aromatic teas, and storytelling under starlit skies, far from city lights. Photographers and nature enthusiasts alike can capture sweeping desert landscapes and dramatic sunsets that transform the horizon into a canvas of gold and orange. These experiences provide a perfect balance to the coastal attractions, offering travelers a chance to connect with the timeless beauty and culture of Egypt’s desert.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['desert','safari','adventure','bedouin']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Local Cuisine in Hurghada',
                'slug' => Str::slug('Local Cuisine in Hurghada'),
                'excerpt' => 'Taste the authentic flavors of Hurghada and the Red Sea.',
                'content' => 'Hurghada’s cuisine is a rich blend of fresh seafood and Arabic culinary traditions. Visitors can enjoy freshly grilled fish, spicy rice dishes, mezze platters, and traditional Egyptian desserts. Coastal restaurants serve catches of the day, while local markets offer spices, fresh vegetables, and handmade delicacies. Dining experiences often combine flavors with scenic views, whether at a beachfront eatery or a bustling local cafe. Culinary tours allow travelers to learn about ingredients, cooking techniques, and the cultural significance of each dish, making every meal both a delight and a learning experience. From casual bites to gourmet feasts, Hurghada’s food scene is as vibrant as its coastlines.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['food','cuisine','seafood','egypt']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Diving in the Red Sea',
                'slug' => Str::slug('Diving in the Red Sea'),
                'excerpt' => 'World-class diving in Hurghada’s crystal-clear waters.',
                'content' => 'Diving in the Red Sea is a premier experience for enthusiasts of all levels. Renowned sites such as Abu Ramada, Fanadir, and Giftun Islands offer incredible visibility, vibrant coral walls, and abundant marine life. Divers encounter schools of tropical fish, reef sharks, turtles, and unique underwater formations, while wreck dives provide historical intrigue. Dive centers across Hurghada provide certified instructors, equipment rental, and guided tours for beginners and professionals alike. Beyond the underwater adventures, the Red Sea coastline offers luxury resorts, desert excursions, and cultural experiences, ensuring that each visit combines exploration, relaxation, and unforgettable memories beneath and above the waves.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['diving','red sea','marine life','adventure']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Historical Sites in Egypt',
                'slug' => Str::slug('Historical Sites in Egypt'),
                'excerpt' => 'Explore pyramids, temples, and ancient monuments.',
                'content' => 'Egypt’s historical sites are unmatched, ranging from the majestic pyramids of Giza to the grand temples of Luxor and Karnak, and from Islamic mosques to Coptic churches. Each monument tells a story of centuries of civilization, reflecting art, religion, and engineering of past cultures. Visitors traveling from Hurghada often take day trips to Luxor, exploring the Valley of the Kings, the Temple of Hatshepsut, and the colossi of Memnon, gaining insight into pharaonic life. Cairo offers the Egyptian Museum and ancient mosques that showcase both Islamic architecture and rich collections of artifacts. These journeys allow tourists to witness the layers of history in a single day, connecting past and present. Experiencing Egypt’s heritage is both educational and awe-inspiring, leaving a deep impression on travelers who come to admire human ingenuity and cultural endurance.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['egypt','history','sites']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Arabic Calligraphy',
                'slug' => Str::slug('Arabic Calligraphy'),
                'excerpt' => 'Artful script connecting language and design.',
                'content' => 'Arabic calligraphy is both a visual art and a form of written expression, transforming letters into intricate, flowing patterns that convey meaning and beauty. It adorns mosques, manuscripts, textiles, and architectural facades, linking spirituality with artistic creativity. Calligraphers often spend years perfecting techniques, exploring proportionality, line flow, and ornamental styles. The flowing lines and geometric arrangements not only beautify text but also symbolize the connection between the divine and human intellect. In cultural contexts, Arabic calligraphy represents history, education, and religious devotion, bridging centuries of tradition. Tourists encountering this art often appreciate its elegance, rhythm, and complexity, making it one of the most celebrated forms of artistic heritage in the Arabic world.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['arabic','calligraphy','art']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hurghada Resorts and Hotels',
                'slug' => Str::slug('Hurghada Resorts and Hotels'),
                'excerpt' => 'Luxury and comfort by the Red Sea.',
                'content' => 'Hurghada offers a wide range of resorts and hotels catering to different budgets and preferences. Luxury resorts feature private beaches, pools, fine dining, spas, and direct access to diving and snorkeling excursions. Mid-range accommodations provide comfortable stays with convenient amenities, often close to beaches or town centers. Many resorts host entertainment programs, cultural shows, and family-friendly activities. The architecture often reflects Arabic or Mediterranean design elements, blending elegance with local flavor. Tourists can choose between quiet retreats for relaxation or vibrant hotels offering lively nightlife. Service and hospitality are emphasized, making every stay memorable. Resorts often act as gateways to explore Hurghada’s natural beauty, from coral reefs to desert landscapes, ensuring that every guest experiences a blend of comfort and adventure.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['hurghada','resorts','hotels']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Cultural Events in Red Sea',
                'slug' => Str::slug('Cultural Events in Red Sea'),
                'excerpt' => 'Festivals, fairs, and concerts celebrating tradition.',
                'content' => 'The Red Sea region hosts a variety of cultural events throughout the year, ranging from music and dance festivals to traditional fairs and art exhibitions. Performances highlight local heritage, featuring Arabic music, folkloric dances, and theatrical displays. Tourists have opportunities to participate in workshops, taste regional cuisine, and explore crafts created by local artisans. These events promote cultural exchange and provide insight into community life. Many festivals take place in open-air venues along the coast, combining scenic landscapes with vibrant cultural expression. Attending these events offers both entertainment and educational value, creating immersive experiences that deepen understanding of the region’s traditions. The atmosphere is festive, inclusive, and celebratory, ensuring that every visitor enjoys a connection to local culture.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['red sea','culture','events']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Music and Dance Performances',
                'slug' => Str::slug('Music and Dance Performances'),
                'excerpt' => 'Traditional shows blending rhythm, instruments, and movement.',
                'content' => 'Evenings in Hurghada often feature captivating music and dance performances, blending traditional Arabic melodies with expressive dance routines. Performers utilize instruments such as the oud, qanun, and darbuka, creating dynamic rhythms that guide dancers’ movements. Shows are commonly held in resorts, cultural centers, and open-air venues, allowing audiences to experience the essence of local entertainment. The performances often tell stories of heritage, love, and community life. Attendees are sometimes invited to participate, adding a communal dimension to the experience. These artistic events help preserve traditions while also appealing to modern tastes, offering a bridge between history and contemporary culture. For tourists, watching these performances provides both enjoyment and a deeper appreciation for Egyptian cultural expression.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['music','dance','performance']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sea Life Photography',
                'slug' => Str::slug('Sea Life Photography'),
                'excerpt' => 'Capturing vibrant underwater life.',
                'content' => 'The Red Sea offers unparalleled opportunities for sea life photography. Its clear waters allow photographers to capture vivid images of coral reefs, colorful fish, and other marine creatures in natural settings. Divers and snorkelers can explore different habitats, from shallow reefs to deeper coral gardens, each providing unique photographic perspectives. Photographers often document rare species, schools of fish, and intricate coral formations, creating visual stories of underwater ecosystems. The combination of natural light, turquoise water, and biodiversity makes the Red Sea a global destination for marine photography. Both amateur and professional photographers enjoy the challenge and beauty of underwater composition. This practice also raises awareness about marine conservation and the importance of preserving delicate ecosystems. Every dive or snorkeling trip offers a chance to create images that inspire wonder and appreciation for marine life.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['sea life','photography','red sea']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Marine Conservation in Red Sea',
                'slug' => Str::slug('Marine Conservation in Red Sea'),
                'excerpt' => 'Protecting the Red Sea’s coral reefs and diverse marine life.',
                'content' => 'Hurghada and the surrounding Red Sea region host several conservation projects aimed at preserving fragile coral reefs, marine biodiversity, and the overall health of the ecosystem. Divers and snorkelers are encouraged to follow eco-friendly practices, including avoiding contact with corals, not collecting marine life, and using reef-safe sunscreens. Local organizations and resorts also run awareness campaigns and volunteer programs, allowing visitors to participate in reef clean-ups and educational tours. Protecting these underwater treasures ensures that future generations can continue to enjoy the vibrant, colorful reefs, the schools of fish, and the extraordinary marine life that make Hurghada a world-class destination for ocean enthusiasts.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['conservation','marine life','reef','red sea']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Hurghada Excursions',
                'slug' => Str::slug('Hurghada Excursions'),
                'excerpt' => 'Island trips, snorkeling tours, and cultural visits from Hurghada.',
                'content' => 'Excursions from Hurghada offer a wide range of experiences for visitors of all ages. Day trips include visits to nearby islands like Giftun and Mahmya, where snorkeling and glass-bottom boat tours reveal the underwater beauty without getting wet. Excursions also extend to nearby towns and desert areas, providing cultural immersion with local markets, Bedouin villages, and historical landmarks. Guided tours provide insight into both marine ecosystems and traditional ways of life, creating a perfect blend of adventure, learning, and relaxation. Each trip adds a new layer of discovery, from the mysteries of the Red Sea to the vibrant traditions of Egypt’s coastal communities.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['excursions','islands','snorkeling','culture']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Traditional Markets and Bazaars',
                'slug' => Str::slug('Traditional Markets and Bazaars'),
                'excerpt' => 'Experience the colors, spices, and crafts of Hurghada’s markets.',
                'content' => 'Hurghada’s traditional markets and bazaars are vibrant centers of local culture. Visitors can stroll through alleys filled with colorful textiles, handmade crafts, aromatic spices, and souvenirs that reflect centuries of artistry. Bargaining is part of the experience, offering both fun and engagement with local vendors. Beyond shopping, walking through the markets provides cultural insights, from culinary traditions to artisan techniques. These bustling marketplaces give travelers a tangible connection to the community, allowing them to take home not only unique items but also unforgettable memories of Hurghada’s lively streets.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['markets','shopping','culture','artisans']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Sunset Cruises',
                'slug' => Str::slug('Sunset Cruises'),
                'excerpt' => 'Romantic and peaceful evening cruises along Hurghada’s coast.',
                'content' => 'Sunset cruises in Hurghada provide breathtaking views of the Red Sea as it reflects the golden hues of the evening sky. Travelers enjoy calm waters, cool breezes, and a relaxing atmosphere aboard traditional boats, luxury yachts, or sailing vessels. Many cruises include refreshments, music, and opportunities for photography, making them ideal for couples, families, or solo travelers seeking tranquility. These excursions offer a unique perspective of the coastline, allowing visitors to witness marine life near the surface and experience the serene beauty of the sea as the sun dips below the horizon.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['sunset','cruise','romantic','red sea']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Coral Reef Exploration',
                'slug' => Str::slug('Coral Reef Exploration'),
                'excerpt' => 'Dive or snorkel among Hurghada’s vibrant coral ecosystems.',
                'content' => 'Hurghada’s coral reefs are among the richest ecosystems in the world, offering an unparalleled experience for divers and snorkelers. Sites like Giftun Islands, Abu Ramada, and Fanadir host colorful coral formations, schools of tropical fish, and other marine creatures that make every dive a visual feast. Guided tours provide safety, equipment, and knowledge about reef ecosystems, ensuring that visitors can fully appreciate the biodiversity without harming it. Exploring these reefs feels like stepping into another universe, where the movement, colors, and life create an immersive adventure that combines excitement with learning about the delicate balance of marine habitats.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['coral reef','snorkeling','diving','marine life']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Water Sports Activities',
                'slug' => Str::slug('Water Sports Activities'),
                'excerpt' => 'Windsurfing, kitesurfing, parasailing, and more in Hurghada.',
                'content' => 'Hurghada is one of Egypt’s top destinations for water sports, thanks to its warm waters, steady winds, and calm seas. Popular activities include windsurfing, kitesurfing, parasailing, and jet skiing, catering to beginners and experienced enthusiasts alike. Many resorts and specialized centers offer lessons, rentals, and guided sessions, ensuring safety and maximizing enjoyment. Beyond adrenaline-fueled adventures, water sports provide a unique way to explore the coastline, enjoy scenic views, and experience the thrill of riding the waves under the Red Sea sun.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['water sports','kitesurfing','windsurfing','adventure']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Local Festivals and Fairs',
                'slug' => Str::slug('Local Festivals and Fairs'),
                'excerpt' => 'Celebrate Hurghada’s heritage with music, food, and dance.',
                'content' => 'Hurghada hosts a variety of local festivals and fairs that celebrate Egypt’s rich heritage. These events bring together tourists and residents in vibrant gatherings filled with music, traditional dancing, culinary delights, and colorful decorations. Visitors can taste authentic dishes, watch performances, and engage with cultural workshops. Festivals often coincide with national holidays, local celebrations, or seasonal events, providing a lively glimpse into community traditions. Participating in these fairs allows travelers to experience the joyous spirit of Hurghada while connecting with the local culture in a memorable and interactive way.',
                'status' => 'published',
                'views' => rand(50,500),
                'tags' => json_encode(['festivals','culture','music','food']),
                'published_at' => Carbon::now()->subDays(rand(0,30)),
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        foreach ($articles as $article) {
            DB::table('blogs')->insert([
                'user_id' => 1,
                'title' => $article['title'],
                'slug' => Str::slug($article['title']),
                'excerpt' => Str::limit($article['content'], 160),
                'content' => $article['content'],
                'status' => 'published',
                'views' => rand(50, 500),
                'tags' => json_encode(explode(' ', strtolower($article['title']))),
                'published_at' => Carbon::now()->subDays(rand(0, 30)),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
