<?php

namespace Database\Seeders;

use App\Models\Hotel;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hotels = [
            [
                'name' => 'Steigenberger Aldau Beach Hotel',
                'category' => 'Luxury Resort',
                'description' => 'A luxurious 5-star beachfront resort offering world-class amenities, multiple restaurants, spa services, and direct access to the pristine Red Sea beaches. Perfect for couples and families seeking an unforgettable vacation experience.',
                'address' => 'Aldau Beach, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2574,
                'longitude' => 33.8129,
                'rating' => 4.5,
                'popularity' => 95,
                'is_featured' => true,
                'price_range' => '$$$$',
                'amenities' => ['Beach Access', 'Spa & Wellness', 'Multiple Restaurants', 'Swimming Pools', 'Water Sports', 'Kids Club', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.steigenberger.com',
                'phone' => '+20 65 346 0000',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Premier Le Reve Hotel & Spa',
                'category' => 'Adults Only Resort',
                'description' => 'An exclusive adults-only 5-star resort featuring elegant accommodations, award-winning spa facilities, and romantic beachfront dining. Ideal for honeymooners and couples looking for a peaceful, sophisticated retreat.',
                'address' => 'Sahl Hasheesh, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.1234,
                'longitude' => 33.8567,
                'rating' => 4.7,
                'popularity' => 88,
                'is_featured' => true,
                'price_range' => '$$$$',
                'amenities' => ['Adults Only', 'Spa & Wellness', 'Beach Access', 'Fine Dining', 'Swimming Pools', 'Romantic Packages', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.premierlereve.com',
                'phone' => '+20 65 346 1111',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Albatros Palace Resort',
                'category' => 'Family Resort',
                'description' => 'A family-friendly 5-star resort with extensive entertainment facilities, multiple swimming pools, and dedicated children\'s areas. Features all-inclusive packages and a wide range of activities for all ages.',
                'address' => 'Sahl Hasheesh, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.1345,
                'longitude' => 33.8678,
                'rating' => 4.3,
                'popularity' => 92,
                'is_featured' => true,
                'price_range' => '$$$',
                'amenities' => ['All Inclusive', 'Kids Club', 'Multiple Pools', 'Beach Access', 'Entertainment', 'Water Sports', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.albatrosresorts.com',
                'phone' => '+20 65 346 2222',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Sunrise Garden Beach Resort',
                'category' => 'Beach Resort',
                'description' => 'A beautiful 5-star beachfront resort offering stunning Red Sea views, excellent diving facilities, and traditional Egyptian hospitality. Perfect for water sports enthusiasts and beach lovers.',
                'address' => 'Km 20 Hurghada – Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2456,
                'longitude' => 33.8234,
                'rating' => 4.2,
                'popularity' => 85,
                'is_featured' => false,
                'price_range' => '$$$',
                'amenities' => ['Beach Access', 'Diving Center', 'Water Sports', 'Swimming Pools', 'Restaurants', 'Spa', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.sunrisegarden.com',
                'phone' => '+20 65 346 3333',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Hilton Hurghada Resort',
                'category' => 'International Chain',
                'description' => 'A trusted 5-star international resort brand offering reliable service, modern amenities, and beautiful beachfront location. Features multiple dining options and comprehensive business facilities.',
                'address' => 'Hurghada Marina, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2567,
                'longitude' => 33.8345,
                'rating' => 4.4,
                'popularity' => 90,
                'is_featured' => true,
                'price_range' => '$$$$',
                'amenities' => ['Beach Access', 'Business Center', 'Multiple Restaurants', 'Swimming Pools', 'Spa', 'Fitness Center', 'Concierge', 'Free WiFi'],
                'website' => 'https://www.hilton.com',
                'phone' => '+20 65 346 4444',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Marlin Inn Azur Resort',
                'category' => 'Boutique Resort',
                'description' => 'A charming 4-star boutique resort offering personalized service and intimate atmosphere. Perfect for travelers seeking a more authentic and peaceful experience away from large crowds.',
                'address' => 'Touristic Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2678,
                'longitude' => 33.8456,
                'rating' => 4.1,
                'popularity' => 78,
                'is_featured' => false,
                'price_range' => '$$',
                'amenities' => ['Beach Access', 'Restaurant', 'Swimming Pool', 'Spa', 'Water Sports', 'Fitness Center', 'Free WiFi', 'Airport Shuttle'],
                'website' => 'https://www.marlininn.com',
                'phone' => '+20 65 346 5555',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Magic Beach Hotel Hurghada',
                'category' => 'Family Hotel',
                'description' => 'A family-oriented 4-star hotel with excellent facilities for children and adults. Features a private beach, multiple pools, and entertainment programs suitable for all family members.',
                'address' => 'El Helal District, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2789,
                'longitude' => 33.8567,
                'rating' => 4.0,
                'popularity' => 82,
                'is_featured' => false,
                'price_range' => '$$',
                'amenities' => ['Private Beach', 'Kids Club', 'Swimming Pools', 'Restaurant', 'Entertainment', 'Water Sports', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.magicbeach.com',
                'phone' => '+20 65 346 6666',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Grand Seas Resort & Aqua Park',
                'category' => 'Aqua Park Resort',
                'description' => 'An exciting 4-star resort featuring a large aqua park with thrilling water slides and attractions. Perfect for families with children and water park enthusiasts seeking fun and adventure.',
                'address' => 'KM 14 - Hurghada - Safaga Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.2890,
                'longitude' => 33.8678,
                'rating' => 4.2,
                'popularity' => 87,
                'is_featured' => true,
                'price_range' => '$$$',
                'amenities' => ['Aqua Park', 'Water Slides', 'Beach Access', 'Kids Club', 'Swimming Pools', 'Restaurants', 'Entertainment', 'Free WiFi'],
                'website' => 'https://www.grandseas.com',
                'phone' => '+20 65 346 7777',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'The Chedi El Gouna',
                'category' => 'Luxury Boutique',
                'description' => 'An exclusive 5-star luxury boutique hotel offering sophisticated accommodations and personalized service. Features contemporary design, gourmet dining, and serene spa facilities in the beautiful El Gouna area.',
                'address' => 'The Hill, El Gouna, Red Sea Governorate, Egypt',
                'latitude' => 27.3901,
                'longitude' => 33.6789,
                'rating' => 4.8,
                'popularity' => 94,
                'is_featured' => true,
                'price_range' => '$$$$',
                'amenities' => ['Luxury Spa', 'Gourmet Dining', 'Private Beach', 'Concierge', 'Fitness Center', 'Water Sports', 'Free WiFi', 'Airport Transfer'],
                'website' => 'https://www.ghmhotels.com',
                'phone' => '+20 65 346 8888',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Fanadir Hotel El Gouna',
                'category' => 'Marina Hotel',
                'description' => 'A stylish 4-star hotel located in the heart of El Gouna\'s marina district. Offers easy access to shopping, dining, and entertainment venues while providing comfortable accommodations and excellent service.',
                'address' => 'Abu Tig Marina North Basin, El Gouna, Red Sea Governorate, Egypt',
                'latitude' => 27.4012,
                'longitude' => 33.6890,
                'rating' => 4.3,
                'popularity' => 80,
                'is_featured' => false,
                'price_range' => '$$$',
                'amenities' => ['Marina Location', 'Restaurant', 'Swimming Pool', 'Spa', 'Shopping Access', 'Water Sports', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.fanadir.com',
                'phone' => '+20 65 346 9999',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'MinaMark Beach Resort',
                'category' => 'Beach Resort',
                'description' => 'A comfortable 4-star beachfront resort offering great value for money with direct beach access and modern amenities. Ideal for budget-conscious travelers who don\'t want to compromise on quality.',
                'address' => 'Sheraton Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.3123,
                'longitude' => 33.8901,
                'rating' => 3.9,
                'popularity' => 75,
                'is_featured' => false,
                'price_range' => '$$',
                'amenities' => ['Beach Access', 'Swimming Pool', 'Restaurant', 'Water Sports', 'Fitness Center', 'Free WiFi', 'Airport Shuttle', 'Tour Desk'],
                'website' => 'https://www.minamark.com',
                'phone' => '+20 65 346 0001',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Amarina Abu Soma Resort & Aquapark',
                'category' => 'Aqua Park Resort',
                'description' => 'A fantastic 5-star resort featuring an impressive aqua park with multiple slides and water attractions. Located in the beautiful Soma Bay area, offering pristine beaches and excellent diving opportunities.',
                'address' => 'KM 8 Safaga Road, Soma Bay, Red Sea Governorate, Egypt',
                'latitude' => 27.3234,
                'longitude' => 33.9012,
                'rating' => 4.4,
                'popularity' => 89,
                'is_featured' => true,
                'price_range' => '$$$',
                'amenities' => ['Aqua Park', 'Beach Access', 'Diving Center', 'Kids Club', 'Swimming Pools', 'Restaurants', 'Spa', 'Free WiFi'],
                'website' => 'https://www.amarina.com',
                'phone' => '+20 65 346 0002',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Lilly Apartments',
                'category' => 'Apartment Hotel',
                'description' => 'Comfortable 4-star apartment-style accommodations perfect for extended stays and families. Features fully equipped kitchens, spacious living areas, and access to resort amenities.',
                'address' => 'El Hadaba Road, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.3345,
                'longitude' => 33.9123,
                'rating' => 3.8,
                'popularity' => 70,
                'is_featured' => false,
                'price_range' => '$$',
                'amenities' => ['Kitchen Facilities', 'Swimming Pool', 'Restaurant', 'Fitness Center', 'Free WiFi', 'Airport Shuttle', 'Laundry Service', 'Tour Desk'],
                'website' => 'https://www.lillyapartments.com',
                'phone' => '+20 65 346 0003',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Cecelia Resort Compound',
                'category' => 'Resort Complex',
                'description' => 'A comprehensive resort complex offering various accommodation types from hotel rooms to private villas. Features extensive facilities including multiple pools, restaurants, and recreational activities.',
                'address' => 'Cecelia Resort, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.3456,
                'longitude' => 33.9234,
                'rating' => 4.1,
                'popularity' => 83,
                'is_featured' => false,
                'price_range' => '$$$',
                'amenities' => ['Multiple Pools', 'Beach Access', 'Restaurants', 'Spa', 'Water Sports', 'Kids Club', 'Fitness Center', 'Free WiFi'],
                'website' => 'https://www.ceceliaresort.com',
                'phone' => '+20 65 346 0004',
                'stars' => 4,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop'
            ],
            [
                'name' => 'Hurghada Marriott Beach Resort',
                'category' => 'International Chain',
                'description' => 'A prestigious 5-star Marriott resort offering world-class service and amenities. Features elegant accommodations, multiple dining venues, and comprehensive business and leisure facilities.',
                'address' => 'Hurghada Marina, Hurghada, Red Sea Governorate, Egypt',
                'latitude' => 27.3567,
                'longitude' => 33.9345,
                'rating' => 4.6,
                'popularity' => 91,
                'is_featured' => true,
                'price_range' => '$$$$',
                'amenities' => ['Beach Access', 'Business Center', 'Multiple Restaurants', 'Swimming Pools', 'Spa', 'Fitness Center', 'Concierge', 'Free WiFi'],
                'website' => 'https://www.marriott.com',
                'phone' => '+20 65 346 0005',
                'stars' => 5,
                'check_in_time' => '15:00',
                'check_out_time' => '12:00',
                'image_url' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop'
            ]
        ];

        foreach ($hotels as $hotelData) {
            Hotel::create($hotelData);
        }
    }
}
